### ISSUE TITLE
Padroniza documentação básica de repositórios

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario-comunidade#14]
A documentação básica de todos os repositórios do Querido Diário devem ter:

1. Na raiz:
- LICENSE.md; arquivo de mesmo conteúdo em todos os repositórios 
- Diretório /docs

2. No diretório /docs conter:
- CODE_OF_CONDUCT.md e suas traduções; deve apontar para CODE_OF_CONDUCT.md de comunidade 
- FUNDING.yml; arquivo de mesmo conteúdo em todos os repositórios 
- SUPPORT.md e suas traduções; arquivo de mesmo conteúdo em todos os repositórios
- README.md com layout padronizado e suas traduções
- CONTRIBUTING.md com layout padronizado e suas traduções; deve apontar para CONTRIBUTING.md de comunidade e conter partes específicas ao repositório

## REPOSITÓRIOS COBERTOS
- [x] querido-diario 
PR: okfn-brasil/querido-diario/pull/605
- [x] querido-diario-comunidade 
PR: #17
- [x] querido-diario-frontend
PR: okfn-brasil/querido-diario-frontend/pull/60 
- [x] querido-diario-api
PR: okfn-brasil/querido-diario-api/pull/57
- [x] querido-diario-api-wrapper
PR: okfn-brasil/querido-diario-api-wrapper/pull/4
- [x] querido-diario-data-processing
PR: okfn-brasil/querido-diario-data-processing/pull/29
- [x] querido-diario-toolbox 
PR: okfn-brasil/querido-diario-toolbox#45
- [x] querido-diario-backend
PR: https://github.com/okfn-brasil/querido-diario-backend/pull/1
- [] querido-diario-infra

**Comment by trevineju** [comment]
Situação do repositório querido-diario-comunidade:

Na raiz:
- [ok] README.md
- [ok] Diretório .github

No diretório .github conter:
- [ok] CODE_OF_CONDUCT.md e suas traduções 
- [ok] CONTRIBUTING.md e suas traduções
- [ok] FUNDING.yml 
- [ok] SUPPORT.md e suas traduções
- [ ] LICENSE.md 
- [ok] E as traduções do README.md 

PR para corrigir o item faltante:
#13

**Comment by trevineju** [comment]
Situação do repositório querido-diario-frontend:

Na raiz:
- [ok] README.md
- [ok] Diretório .github

No diretório .github conter:
- [ok] CODE_OF_CONDUCT.md e suas traduções; aponta para CODE_OF_CONDUCT.md de comunidade 
- [ ] CONTRIBUTING.md e suas traduções; aponta para CONTRIBUTING.md de comunidade
- [ok] FUNDING.yml; igual ao de comunidade 
- [ok] SUPPORT.md e suas traduções; igual ao de comunidade
- [ ] LICENSE.md; igual ao de comunidade 
- [ok] E as traduções do README.md 

PR para corrigir o item faltante:
#https://github.com/okfn-brasil/querido-diario-frontend/pull/60

**Comment by trevineju** [comment]
Situação do repositório querido-diario:

Na raiz:
- [ok] README.md
- [ok] Diretório .github

No diretório .github conter:
- [ ] CODE_OF_CONDUCT.md e suas traduções; aponta para CODE_OF_CONDUCT.md de comunidade 
- [ ] CONTRIBUTING.md e suas traduções; aponta para CONTRIBUTING.md de comunidade
- [ ] FUNDING.yml; igual ao de comunidade 
- [ ] SUPPORT.md e suas traduções; igual ao de comunidade
- [ ] LICENSE.md; igual ao de comunidade 
- [ ] E as traduções do README.md 

PR para corrigir os itens faltantes:

**Comment by trevineju** [comment]
Situação do repositório **querido-diario-api**:

Na raiz:
- [ok] README.md
- [ok] Diretório .github

No diretório .github conter:
- [ ] CODE_OF_CONDUCT.md e suas traduções; aponta para CODE_OF_CONDUCT.md de comunidade 
- [ ] CONTRIBUTING.md e suas traduções; aponta para CONTRIBUTING.md de comunidade
- [ ] FUNDING.yml; igual ao de comunidade 
- [ ] SUPPORT.md e suas traduções; igual ao de comunidade
- [ ] LICENSE.md; igual ao de comunidade 
- [ ] E as traduções do README.md 

PR para corrigir os itens faltantes:

**Comment by trevineju** [comment]
Situação do repositório **querido-diario-api-wrapper**:

Na raiz:
- [ok] README
- [ ] Diretório .github

No diretório .github conter:
- [ ] CODE_OF_CONDUCT.md e suas traduções; aponta para CODE_OF_CONDUCT.md de comunidade 
- [ ] CONTRIBUTING.md e suas traduções; aponta para CONTRIBUTING.md de comunidade
- [ ] FUNDING.yml; igual ao de comunidade 
- [ ] SUPPORT.md e suas traduções; igual ao de comunidade
- [ ] LICENSE.md; igual ao de comunidade 
- [ ] E as traduções do README.md -- _não há_

PR para corrigir os itens faltantes:

**Comment by trevineju** [comment]
Situação do repositório **querido-diario-data-processing**:

Na raiz:
- [ok] README
- [ok] Diretório .github

No diretório .github conter:
- [ ] CODE_OF_CONDUCT.md e suas traduções; aponta para CODE_OF_CONDUCT.md de comunidade 
- [ ] CONTRIBUTING.md e suas traduções; aponta para CONTRIBUTING.md de comunidade
- [ ] FUNDING.yml; igual ao de comunidade 
- [ ] SUPPORT.md e suas traduções; igual ao de comunidade
- [ ] LICENSE.md; igual ao de comunidade 
- [ ] E as traduções do README.md

PR para corrigir os itens faltantes:

**Comment by trevineju** [comment]
Situação do repositório **querido-diario-toolbox**:

Na raiz:
- [ok] README.md
- [ok] Diretório .github

No diretório .github conter:
- [ ] CODE_OF_CONDUCT.md e suas traduções; aponta para CODE_OF_CONDUCT.md de comunidade 
- [ ] CONTRIBUTING.md e suas traduções; aponta para CONTRIBUTING.md de comunidade
- [ ] FUNDING.yml; igual ao de comunidade 
- [ ] SUPPORT.md e suas traduções; igual ao de comunidade
- [ ] LICENSE.md; igual ao de comunidade 
- [ ] E as traduções do README.md 

PR para corrigir os itens faltantes:

**Comment by trevineju** [comment]
Situação do repositório **querido-diario-infra**:

Na raiz:
- [ok] README.md
- [ ] Diretório .github

No diretório .github conter:
- [ ] CODE_OF_CONDUCT.md e suas traduções; aponta para CODE_OF_CONDUCT.md de comunidade 
- [ ] CONTRIBUTING.md e suas traduções; aponta para CONTRIBUTING.md de comunidade
- [ ] FUNDING.yml; igual ao de comunidade 
- [ ] SUPPORT.md e suas traduções; igual ao de comunidade
- [ ] LICENSE.md; igual ao de comunidade 
- [ ] E as traduções do README.md -- _não há_

PR para corrigir os itens faltantes:

**Comment by lguima** [comment]
oi @trevineju! o arquivo de licença costuma ficar na raiz do repo mesmo

**Comment by trevineju** [comment]
@lguima obrigada pelo apontamento! Vou corrigir. Aproveitei também pra alimentar a discussão na thread #11 -- que não tinha visto quando abri essa issue. Assim, você e outras pessoas podem complementar os apontamentos de documentação e aí eu sigo trabalhando nesta issue a partir da contribuição de vocês

**Comment by trevineju** [comment]
Movi as licenças de volta para a raiz e nos repositórios que já tinha um `contributing.md` o conteúdo foi adicionado ao arquivo novo para o contributing continuar, pelo menos, com o conteúdo atual, mas ainda sem revisão do texto em si.

**Comment by trevineju** [comment]
PR do repositório querido-diario-toolbox: #https://github.com/okfn-brasil/querido-diario-toolbox/pull/45

**Comment by ogecece** [comment]
O querido-diario-infra foi despriorizado e essa issue está completa.

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
Dear-diario-infra has been deprioritized and this issue is complete.
