### ISSUE TITLE
Padroniza README.md e CONTRIBUTING.md dos repositórios

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario-comunidade#15]
Como trazido na discussão sobre unificar a documentação do QD (Discussion #11), os repositórios também passarão por revisão dos READMEs e CONTRIBUTINGs buscando atender ao modelo conforme possível.

## REPOSITÓRIOS PRONTOS
- [ ] querido-diario
- [ ] querido-diario-comunidade
- [ ] querido-diario-frontend 
- [ ] querido-diario-api
- [ ] querido-diario-api-wrapper
- [ ] querido-diario-data-processing
- [ ] querido-diario-toolbox
- [ ] querido-diario-infra

**Comment by trevineju** [comment]
PR para implementar o padrão no repositório `-comunidade`: #17

**Comment by trevineju** [comment]
PR para implementar o padrão no repositório `querido-diario": #https://github.com/okfn-brasil/querido-diario/pull/643

**Comment by giuliocc** [comment]
Comentei em #17 que achei o Discord meio escondido. Talvez ter uma seção própria seria uma boa

**Comment by trevineju** [comment]
Criei uma seção de Suporte pro Discord. Atualizei o padrão acima com esse item e também já espelhei as correções propostas em #17 para o PR do `querido-diario`.

**Comment by trevineju** [comment]
PR para implementar o padrão no repositório `-frontend`: #https://github.com/okfn-brasil/querido-diario-frontend/pull/76

**Comment by trevineju** [comment]
PR para implementar o padrão no repositório `-toolbox`: #https://github.com/okfn-brasil/querido-diario-toolbox/pull/46

**Comment by trevineju** [comment]
PR em -comunidade: #17

**Comment by trevineju** [comment]
PR em `querido-diario`: [605](https://github.com/okfn-brasil/querido-diario/pull/605)

**Comment by trevineju** [comment]
Demandas desta issue estão sendo atendidas no pela issue #14
