### ISSUE TITLE
Atualizar versão em inglês do README.md

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario-comunidade#16]
É necessário atualizar a tradução no [README em inglês](https://github.com/okfn-brasil/querido-diario-comunidade/blob/main/.github/README-en-US.md) para corresponder ao atual estado do [README em português](https://github.com/okfn-brasil/querido-diario-comunidade/blob/main/README.md).

**Comment by jufajardini** [comment]
Vou trabalhar nessa task :)

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
I'll work on this task :)
