### ISSUE TITLE
Read the Docs: Adicionar página sobre arquitetura do projeto

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario-comunidade#19]
Informações sobre a arquitetura do Querido Diário estão espalhadas em alguns lugares: 
No site, em https://queridodiario.ok.org.br/tecnologia
No contributing.md de `comunidade`: https://github.com/okfn-brasil/querido-diario-comunidade/blob/main/.github/CONTRIBUTING.md

Poderia ser uma página no Read the Docs: https://docs.queridodiario.ok.org.br/pt/latest/index.html

**Comment by isabellazramos** [comment]
Oi! Gostaria de contribuir nessa issue.

**Comment by isabellazramos** [comment]
Em https://queridodiario.ok.org.br/tecnologia , tem uma imagem sobre a arquitetura. No caso como eu colocaria ela? Nos outros arquivos não tem um exemplo sobre...
