### ISSUE TITLE
Melhorias na Documentação da Busca Avançada

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario-comunidade#28]
Como o objetivo do Read the Docs é ser a documentação técnica, dos recursos do Querido Diário, seu conteúdo deve ser enxuto, expondo o suficiente para busca rápidas e localização das respostas facilmente. A referência é a documentação de Python que lista e descreve muito objetivamente para que tal comando serve (exemplo: https://docs.python.org/3/library/string.html?highlight=string#module-string)

Assim, a melhoria na página de busca avançada seria adequá-a nesse modelo de documentação técnica "tradicional". 

Adicionalmente, cada operador de busca não precisa ser um subtítulo, a ponto de ficar explicitado na homepage de docs.queridodiario.ok.org.br. O título basta. 
![image](https://user-images.githubusercontent.com/44185775/197080429-b5c8a1c0-5c99-4fe4-a848-c7e6bf200430.png)

**Comment by trevineju** [comment]
Obrigada você!

**Comment by ricardogando** [comment]
Oi Ju, dúvida: não preciso replicar exatamente o que está na página? É para resumir mais objetivamente.

**Comment by trevineju** [comment]
Isso! Só listar o operador, dizer o que faz numa linha e dar um exemplo (e aí nesse caso sim pode só usar o exemplo já usado) 

Na página de busca, tivemos a preocupação em explicar muito pra atingir as pessoas não técnicas, servindo como "tutorial". No read the docs, é uma documentação pra quem já programa e precisa localizar a resposta rápido. 

Referenciei a docs do python na issue e pode ser bem aquilo mesmo, completamente direto.

**Comment by ogecece** [comment]
O motivo desta issue não existe mais. A documentação de busca avançada agora fica apenas no [site](https://queridodiario.ok.org.br/tecnologia/busca-avancada).

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
The reason for this issue no longer exists. The advanced search documentation is now only on [site](https://queridodiario.ok.org.br/tecnologia/busca-avancada).
