### ISSUE TITLE
Atualizar versão em inglês do CONTRIBUTING.md

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario-comunidade#33]
É necessário atualizar a tradução no [CONTRIBUTING em inglês](https://github.com/okfn-brasil/querido-diario-comunidade/blob/main/.github/CONTRIBUTING-en-US.md) para corresponder ao atual estado do [CONTRIBUTING em português](https://github.com/okfn-brasil/querido-diario-comunidade/blob/main/.github/CONTRIBUTING.md).

**Comment by jufajardini** [comment]
Oi! Posso trabalhar com essa task?
--
Hello! My I work on this issue?

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
Hey! Can I work with this task?
--
Hello! My I work on this issue?
