### ISSUE TITLE
Melhorias no CONTRIBUTING.md

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario-comunidade#35]
No contributing.md de `querido-diario` havia: 
``` 
Sometimes the community organizes events for solving multiple issues in a short amount of time. Especially in these cases, an issue or pull request may be considered abandoned when is waiting for the contributor but doesn't receive updates for a couple of weeks. Just let us know you need more time, so we don't end up closing it by mistake.
```

Este conteúdo deve existir no contributing.md deste repositório

**Comment by trevineju** [comment]
agora, há um repositório de -backend; precisa adicionar à lista do ecossistema

**Comment by jufajardini** [comment]
Posso trabalhar nesta aqui, se não estiver resolvida :)

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
I can work on this one if it's not resolved :)

**Comment by jufajardini** [comment]
> agora, há um repositório de -backend; precisa adicionar à lista do ecossistema

Acho que isso aqui já tá resolvido.

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
> now, there is a -backend repository; need to add to ecosystem list

I think this is already resolved.
