### ISSUE TITLE
Download e exportação de resultados em lote

### ISSUE THREAD

**Issue by ogecece** [okfn-brasil/querido-diario-comunidade#45]
### Descrição
Breve descrição da atividade, sua importância para o Querido Diário e o que seria necessário para completá-la.

**Comment by trevineju** [comment]
Implementado via QD nas Universidades em parceria com a UnB:
- Seleção e download de resultados. 
- Seleção e download da base completa, por ano e por município (aba [Dados](https://queridodiario.ok.org.br/dados))

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
Implemented via QD at Universities in partnership with UnB:
- Selection and download of results. 
- Selection and download of the complete database, by year and by municipality ([Data] tab (https://queridodiario.ok.org.br/dados))
