### ISSUE TITLE
Análise panorâmica #2

### ISSUE THREAD

**Issue by ogecece** [okfn-brasil/querido-diario-comunidade#58]
### Descrição

Segunda análise panorâmica realizada na base do [Querido Diário: Tecnologias na Educação](https://queridodiario.ok.org.br/educacao).

### Escopo da análise (passível de modificação)

- 58 cidades 
- Análise será amostral pelo volume de resultados. Foram eliminadas as duplicatas e foi feito um corte amostral, mantendo 10 resultados por cidade em cada subtema. O critério para exclusão foi temporal - foram eliminados os resultados mais antigos. 
- Escopo temporal: 01/05/2022 a 31/04/2023

**Comment by ogecece** [comment]
### Descrição

Segunda análise panorâmica realizada na base do [Querido Diário: Tecnologias na Educação](https://queridodiario.ok.org.br/educacao).

### Escopo da análise (passível de modificação)

- 58 cidades 
- Análise será amostral pelo volume de resultados. Foram eliminadas as duplicatas e foi feito um corte amostral, mantendo 10 resultados por cidade em cada subtema. O critério para exclusão foi temporal - foram eliminados os resultados mais antigos. 
- Escopo temporal: 01/05/2022 a 31/04/2023

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
### Description

Second panoramic analysis carried out on the basis of [Querido Diário: Tecnologias na Educação](https://queridodiario.ok.org.br/educacao).

### Scope of analysis (subject to modification)

- 58 cities
- Analysis will be sample based on the volume of results. Duplicates were eliminated and a sample cut was made, maintaining 10 results per city in each subtheme. The exclusion criterion was temporal - the oldest results were eliminated.
- Time scope: 05/01/2022 to 04/31/2023

**Comment by trevineju** [comment]
Em 15/12/23, a Panorâmica #2 foi publicada. Foram:
-  75 cidades analisadas
- aplicada a análise amostral sugerida na abertura da issue, totalizando 1555 publicações analisadas
- escopo temporal adotado: 05/2022 a 04/2023. 

Material disponibilizado em: https://queridodiario.ok.org.br/educacao/relatorio/3

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
On 12/15/23, Panoramic #2 was published. They were:
- 75 cities analyzed
- applied the sample analysis suggested at the opening of the issue, totaling 1555 publications analyzed
- adopted temporal scope: 05/2022 to 04/2023.

Material available at: https://queridodiario.ok.org.br/educacao/relatorio/3
