### ISSUE TITLE
Traduzir página sobre "o que é" o Querido Diário para Inglês

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario-comunidade#65]
A página https://docs.queridodiario.ok.org.br/pt/latest/o-que-eh-qd.html precisa ser traduzida para o Inglês. 

O arquivo que gera essa página é: 
https://github.com/okfn-brasil/querido-diario-comunidade/blob/main/docs/o-que-eh.rst 

A tradução deve ser preenchida no arquivo: 
https://github.com/okfn-brasil/querido-diario-comunidade/blob/main/docs/what-is-it.rst

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
The page https://docs.queridodiario.ok.org.br/pt/latest/o-que-eh-qd.html needs to be translated into English.

The file that generates this page is:
https://github.com/okfn-brasil/querido-diario-comunidade/blob/main/docs/source/o-que-eh.rst

The translation must be filled in the file:
https://github.com/okfn-brasil/querido-diario-comunidade/blob/main/docs/source/what-is-it.rst
