### ISSUE TITLE
Traduzir página sobre arquitetura para o Inglês

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario-comunidade#66]
A página https://docs.queridodiario.ok.org.br/pt/latest/arquitetura-do-projeto.html precisa ser traduzida para o Inglês. 

O arquivo que gera essa página é: 
https://github.com/okfn-brasil/querido-diario-comunidade/blob/main/docs/arquitetura.rst

A tradução deve ser preenchida no arquivo: 
https://github.com/okfn-brasil/querido-diario-comunidade/blob/main/docs/architecture.rst

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
The page https://docs.queridodiario.ok.org.br/pt/latest/arquitetura-do-projeto.html needs to be translated into English.

The file that generates this page is:
https://github.com/okfn-brasil/querido-diario-comunidade/blob/main/docs/source/arquitetura.rst

The translation must be filled in the file:
https://github.com/okfn-brasil/querido-diario-comunidade/blob/main/docs/source/architecture.rst

**Comment by MoisesMsa** [comment]
Vou trabalhar nessa

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
I'll work on that
