### ISSUE TITLE
Traduzir página de busca avançada para Inglês

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario-comunidade#68]
A página https://docs.queridodiario.ok.org.br/pt/latest/busca-avancada-nos-diarios.html precisa ser traduzida para o Inglês. 

O arquivo que gera essa página é: 
https://github.com/okfn-brasil/querido-diario-comunidade/blob/main/docs/busca-avancada.rst

A tradução deve ser preenchida no arquivo: 
https://github.com/okfn-brasil/querido-diario-comunidade/blob/main/docs/advanced-search.rst

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
The page https://docs.queridodiario.ok.org.br/pt/latest/busca-avancada-nos-diarios.html needs to be translated into English.

The file that generates this page is:
https://github.com/okfn-brasil/querido-diario-comunidade/blob/main/docs/source/busca-avancada.rst

The translation must be filled in the file:
https://github.com/okfn-brasil/querido-diario-comunidade/blob/main/docs/source/advanced-search.rst

**Comment by camilacruz-cs** [comment]
![image](https://github.com/okfn-brasil/querido-diario-comunidade/assets/91263811/23b51522-add6-4a66-a0f3-112d834c1a90)

Essa demanda ainda tá ativa?

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
![image](https://github.com/okfn-brasil/querido-diario-comunidade/assets/91263811/23b51522-add6-4a66-a0f3-112d834c1a90)

Is this demand still active?

**Comment by trevineju** [comment]
@camilacruz-cs sim! corrigi o link. Ontem precisei fazer uma correção no repositório e aí quebrou o link. Mas agora está certo. Tanto essa issue, como as demais

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
@camilacruz-cs yes! I corrected the link. Yesterday I needed to make a correction to the repository and then the link broke. But now it's right. Both this issue and the others

**Comment by trevineju** [comment]
Vou fazer essa issue!

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
I'm going to make this issue!
