### ISSUE TITLE
Traduzir página "Utilizando a Toolbox" para Inglês

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario-comunidade#69]
A página https://docs.queridodiario.ok.org.br/pt/latest/utilizando-a-toolbox.html precisa ser traduzida para o Inglês.

O arquivo que gera essa página é:
https://github.com/okfn-brasil/querido-diario-comunidade/blob/main/docs/utilizando-a-toolbox.rst

A tradução deve ser preenchida no arquivo:
https://github.com/okfn-brasil/querido-diario-comunidade/blob/main/docs/using-the-toolbox.rst

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
The page https://docs.queridodiario.ok.org.br/pt/latest/utilizando-o-toolbox.html needs to be translated into English.

The file that generates this page is:
https://github.com/okfn-brasil/querido-diario-comunidade/blob/main/docs/source/utilizando-a-toolbox.rst

The translation must be filled in the file:
https://github.com/okfn-brasil/querido-diario-comunidade/blob/main/docs/source/using-the-toolbox.rst

**Comment by itepifanio** [comment]
Trabalhando nessa task @trevineju

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
Working on this task @trevineju
