### ISSUE TITLE
Casos #01, #02 e #03

### ISSUE THREAD

**Issue by ogecece** [okfn-brasil/querido-diario-comunidade#79]
### Descrição

Casos de destaque encontrados na [Análise temática #1](https://queridodiario.ok.org.br/educacao/relatorio/2) (temática: Conectividade) que serão investigados mais a fundo e publicados no [Querido Diário: Tecnologias na Educação](https://queridodiario.ok.org.br/educacao).

**Comment by ogecece** [comment]
### Descrição

Casos de destaque encontrados na [Análise temática #1](https://queridodiario.ok.org.br/educacao/relatorio/2) (temática: Conectividade) que serão investigados mais a fundo e publicados no [Querido Diário: Tecnologias na Educação](https://queridodiario.ok.org.br/educacao).

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
### Description

Highlight cases found in [Thematic Analysis #1](https://queridodiario.ok.org.br/educacao/relatorio/2) (theme: Connectivity) that will be investigated further and published in [Querido Diario: Tecnologias na Education](https://queridodiario.ok.org.br/educacao).

**Comment by ogecece** [comment]
["Internet patrocinada em Florianópolis (SC)": caso #01 publicado em 20/09/23](https://querido-diario-static.nyc3.cdn.digitaloceanspaces.com/documents/education/cases/caso-01.pdf)

**Comment by ogecece** [comment]
["Internet patrocinada em Recife (PE)": caso #02 publicado em 10/10/23](https://querido-diario-static.nyc3.cdn.digitaloceanspaces.com/documents/education/cases/caso-02.pdf)

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
["Sponsored Internet in Recife (PE)": case #02 published on 10/10/23](https://querido-diario-static.nyc3.cdn.digitaloceanspaces.com/documents/education/cases/caso-02 .pdf)

**Comment by trevineju** [comment]
["Internet patrocinada em Salvador (BA)": caso #03 publicado em 01/11/23](https://querido-diario-static.nyc3.cdn.digitaloceanspaces.com/documents/education/cases/caso-03.pdf)

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
["Sponsored Internet in Salvador (BA)": case #03 published on 11/01/23](https://querido-diario-static.nyc3.cdn.digitaloceanspaces.com/documents/education/cases/caso-03 .pdf)
