### ISSUE TITLE
Adicionar o querido-diario-tutorial como documentação para iniciantes em raspagem

### ISSUE THREAD

**Issue by ogecece** [okfn-brasil/querido-diario-comunidade#84]
Em https://github.com/okfn-brasil/querido-diario-frontend/issues/214 o tutorial será adicionado ao blog do QD, mas podemos manter uma versão na documentação técnica (em português e inglês) depois que o texto ficar pronto.

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
At https://github.com/okfn-brasil/querido-diario-frontend/issues/214 the tutorial will be added to the QD blog, but we can maintain a version in the technical documentation (in Portuguese and English) after the text is published. done.

**Comment by trevineju** [comment]
A aba Raspadores da documentação técnica contempla elementos de tutorial - https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
The Scrapers tab of the technical documentation includes tutorial elements - https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html
