### ISSUE TITLE
Análise temática #2

### ISSUE THREAD

**Issue by ogecece** [okfn-brasil/querido-diario-comunidade#94]
### Descrição

Segunda análise temática realizada na base do [Querido Diário: Tecnologias na Educação](https://queridodiario.ok.org.br/educacao).

### Escopo da análise (passível de modificação)

- Tema: Inteligência artifical nas escolas municipais
- Metodologia: Seleção de destaques identificados no [Panorama #2](https://queridodiario.ok.org.br/educacao/relatorio/3) complementados por resultados de buscas específicas na base. Aprofundamento nos destaques por meio de informações publicadas pelos órgãos por transparência ativa e também realização de pedidos via LAI.
- Escopo temporal: 01/05/2022 a 31/04/2023

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
### Description

Second thematic analysis carried out on the basis of [Querido Diário: Tecnologias na Educação](https://queridodiario.ok.org.br/educacao).

### Scope of analysis (subject to modification)

- Theme: Artificial intelligence in municipal schools
- Methodology: Selection of highlights identified in Panorama #2 complemented by results from specific searches in the database. Deepening the highlights through information published by bodies for active transparency and also making requests via LAI.
- Time scope: 05/01/2022 to 04/31/2023

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
Completed, with the publication of the thematic analysis at: https://queridodiario.ok.org.br/educacao/relatorio/4
